- hosts: all
  become: yes
  tasks:
  - name: Add {{ sudo_user }} user
    user:
      name: '{{ sudo_user }}'
      groups: sudo,docker
      append: true
      state: present
      createhome: true
      shell: /bin/bash

  - name: Make sudo without password for {{ sudo_user }} user
    copy:
      dest: /etc/sudoers.d/80-ansible-sudo-user
      content: '{{ sudo_user }} ALL=(ALL) NOPASSWD:ALL'
      mode: '0440'

  - name: Create .ssh directory for {{ sudo_user }}
    ansible.builtin.file:
      path: '/home/{{ sudo_user }}/.ssh'
      state: directory
      mode: '0755'

  - name: Create authorized_keys
    ansible.builtin.copy:
      src: /root/.ssh/authorized_keys
      dest: '/home/{{ sudo_user }}/.ssh/authorized_keys'
      remote_src: true
      owner: '{{ sudo_user }}'
      group: '{{ sudo_user }}'
      mode: '600'
